echo "this script will remove all packages and librarys that came with chromebrew. and that you CAN NOT be in root
in order to run this script. you may or may not get many errors, depending on how many packages 
you have installed. you now have 10 seconds to press ctrl + c should you want to cancel."
sleep 15
echo 10
sleep 1
echo 9
sleep 1
echo 8
sleep 1
echo 7
sleep 1
echo 6
sleep 1
echo 5
sleep 1
echo 4
sleep 1
echo 3
sleep 1
echo 2
sleep 1
echo 1
sleep 1
echo 0
sleep 1
echo "the script will now uninstall packages."
crew remove a2png
crew remove a2ps
crew remove a52
crew remove aalib
crew remove abcde
crew remove acl
crew remove ag
crew remove aide
crew remove aircrack_ng
crew remove alive
crew remove alsa_lib
crew remove alsa_plugins
crew remove anagram
crew remove ansible
crew remove ansifilter
crew remove ant
crew remove antiword
crew remove antlr4
crew remove apr
crew remove apriconv
crew remove aprutil
crew remove arduino_ide
crew remove argon2
crew remove aria2
crew remove armadillo
crew remove asciidoc
crew remove asciinema
crew remove aspell
crew remove aspell_en
crew remove aspell_es
crew remove atkmm
crew remove atomicparsley
crew remove atool
crew remove autoconf_archive
crew remove autosetup
crew remove aview
crew remove avocado
crew remove aws
crew remove aws_shell
crew remove axel
crew remove az
crew remove babl
crew remove bacon
crew remove banner
crew remove bash_completion
crew remove bashdb
crew remove bats
crew remove bcif
crew remove bdwgc
crew remove biew
crew remove binclock
crew remove bind
crew remove bitpocket
crew remove bluefish
crew remove bmon
crew remove boost
crew remove box
crew remove brotli
crew remove buildessential
crew remove byobu
crew remove c_ares
crew remove cabal
crew remove cabextract
crew remove cadaver
crew remove cairomm
crew remove calcurse
crew remove camp
crew remove cbase
crew remove ccl
crew remove cdargs
crew remove cdrkit
crew remove cf
crew remove cgroupfs_mount
crew remove charm
crew remove checkinstall
crew remove chicken
crew remove choose
crew remove chromebeer
crew remove chromebrew_scripts
crew remove chruby
crew remove clamav
crew remove clean
crew remove clib
crew remove clisp
crew remove clmystery
crew remove clojure
crew remove cloog
crew remove code
crew remove collectl
crew remove colordiff
crew remove commacd
crew remove composer
crew remove coreutils
crew remove cowsay
crew remove cpio
crew remove cppunit
crew remove cpustat
crew remove cracklib
crew remove crew_profile
crew remove cronie
crew remove cros_resize
crew remove cryptsetup
crew remove csvkit
crew remove ctags
crew remove ctorrent
crew remove cups
crew remove cvs
crew remove daq
crew remove darkhttpd
crew remove datamash
crew remove dconf
crew remove dehtml
crew remove dejagnu
crew remove desktop_file_utilities
crew remove detox
crew remove dfc
crew remove di
crew remove dia
crew remove diskscan
crew remove disktype
crew remove dmidecode
crew remove crew remove docbook2x
crew remove docutils
crew remove docx2txt
crew remove dos2unix
crew remove dr
crew remove dropbox
crew remove dropbox_uploader
crew remove crew remove dstat
crew remove dtrx
crew remove dub
crew remove duplicity
crew remove ed
crew remove elinks
crew remove elixir
crew remove emacs
crew remove enchant
crew remove enscript
crew remove entr
crew remove erlang
crew remove eventstat
crew remove exif
crew remove expect
crew remove fakeroot
crew remove fakeroot_ng
crew remove far
crew remove fasd
crew remove fetch
crew remove ffcall
crew remove figlet
crew remove filezilla
crew remove finch
crew remove firejail
crew remove fish
crew remove flac
crew remove fly
crew remove fnotifystat
crew remove fop
crew remove foremost
crew remove forkstat
crew remove fortune
crew remove fortunes
crew remove fossil
crew remove fpc
crew remove freebasic
crew remove freedos
crew remove freeglut
crew remove fslint
crew remove fswatch
crew remove fzf
crew remove gb
crew remove gc
crew remove gcc
crew remove gdal
crew remove gdb
crew remove gdrive
crew remove gegl
crew remove gemacs
crew remove gengetopt
crew remove genstats
crew remove geoip
crew remove geos
crew remove get_iplayer
crew remove gexiv2
crew remove ghc
crew remove ghostscript
crew remove gifgen
crew remove giflib
crew remove gifsicle
crew remove gimp
crew remove git_lfs
crew remove github_release
crew remove glfw
crew remove glib_networking
crew remove glibmm
crew remove glide
crew remove glm
crew remove glog
crew remove glyr
crew remove gnome_common
crew remove gnome_docking_library
crew remove gnome_icon_theme
crew remove gnome_themes_standard
crew remove gnucobol
crew remove gnupg
crew remove gnuplot
crew remove go
crew remove go_bootstrap
crew remove goaccess
crew remove google_cloud_sdk
crew remove gox
crew remove gpart
crew remove gpgme
crew remove gptfdisk
crew remove grabinfo
crew remove gradle
crew remove graphicsmagick
crew remove graphviz
crew remove grive
crew remove gsettings_desktop_schemas
crew remove gsl
crew remove gst_plugins_base
crew remove gstreamer
crew remove gtk_engines_adwaita
crew remove gtkmm2
crew remove gtkmm3
crew remove gtkvte
crew remove gtypist
crew remove gucharmap
crew remove guile
crew remove gusb
crew remove gvim
crew remove gwt
crew remove halibut
crew remove haproxy
crew remove has
crew remove hdparm
crew remove health_check
crew remove healthcheck
crew remove help2info
crew remove help2man
crew remove heroku
crew remove hexedit
crew remove hplip
crew remove htop
crew remove httpd
crew remove httrack
crew remove hub
crew remove hunspell
crew remove ibmonitor
crew remove icon_naming_utils
crew remove iftop
crew remove ilmbase
crew remove imagemagick
crew remove imagemagick6
crew remove imagemagick7
crew remove imgur
crew remove inetutils
crew remove inkscape
crew remove inxi
crew remove iperf3
crew remove ipfs
crew remove iptables
crew remove iptraf
crew remove irssi
crew remove itstool
crew remove jam
crew remove jansson
crew remove jdk8
crew remove jfrog
crew remove jobscheduler
crew remove jq
crew remove json2xml
crew remove json_glib
crew remove jsonc
crew remove jsoncpp
crew remove julia
crew remove kakoune
crew remove kbfsfuse
crew remove kbfsgit
crew remove keybase
crew remove keychain
crew remove kore
crew remove kotlin
crew remove kr
crew remove kubectl
crew remove kwiml
crew remove lcms
crew remove ld_default
crew remove ldc
crew remove leveldb
crew remove lft
crew remove lha
crew remove libarchive
crew remove libart
crew remove libassuan
crew remove libatomic_ops
crew remove libav
crew remove libcaca
crew remove libcap
crew remove libcerf
crew remove libcheck
crew remove libconfig
crew remove libconfuse
crew remove libcroco
crew remove libcyrussasl
crew remove libdb
crew remove libde265
crew remove libdnet
crew remove libemf
crew remove libevdev
crew remove libevent
crew remove libexif
crew remove libexiv2
crew remove libfilezilla
crew remove libgd
crew remove libglade
crew remove libglu
crew remove libgnomecanvas
crew remove libgsf
crew remove libgudev
crew remove libheif
crew remove libid3tag
crew remove libinput
crew remove libjpeg_turbo
crew remove libksba
crew remove liblapack
crew remove libmad
crew remove libmicrohttpd
crew remove libmnl
crew remove libmypaint
crew remove libnftnl
crew remove libnotify
crew remove libomxil_bellagio
crew remove libpeas
crew remove libplist
crew remove libprelude
crew remove libproxy
crew remove libpth
crew remove librhash
crew remove librsvg
crew remove librsync
crew remove libseccomp
crew remove libsecret
crew remove libsigcplusplus
crew remove libsigcplusplus3
crew remove libslz
crew remove libsndfile
crew remove libsodium
crew remove libsoup
crew remove libssh
crew remove libticables2
crew remove libticalcs2
crew remove libticonv
crew remove libtifiles2
crew remove libtinfo
crew remove libudev_stub
crew remove libuninum
crew remove libusbmuxd
crew remove libuuid
crew remove libuv
crew remove libvisual
crew remove libvisual_plugins
crew remove libwacom
crew remove libwmf
crew remove libxdmcp
crew remove llvm
crew remove log4cplus
crew remove lsb_release
crew remove lsscsi
crew remove lua
crew remove luajit
crew remove lynis
crew remove lz4
crew remove lzma
crew remove madplay
crew remove mapserver
crew remove markdown
crew remove masscan
crew remove mate_calc
crew remove mate_common
crew remove mate_desktop
crew remove maven
crew remove mc
crew remove mdp
crew remove megatools
crew remove memcached
crew remove mercurial
crew remove metasploit
crew remove mg
crew remove micro
crew remove minerd
crew remove miniconda3
crew remove miniupnpc
crew remove misctools
crew remove mm_common
crew remove moc
crew remove mongodb
crew remove mono
crew remove moreutils
crew remove mosh
crew remove mp4v2
crew remove msttcorefonts
crew remove mtdev
crew remove mtools
crew remove multitail
crew remove muparser
crew remove mutt
crew remove mypaint_brushes
crew remove mysqltuner
crew remove mywanip
crew remove nano
crew remove nanomsg
crew remove nasm
crew remove ncat
crew remove ncdc
crew remove ncdu
crew remove ncftp
crew remove ncrack
crew remove ndisc6
crew remove neofetch
crew remove neovim
crew remove netcat
crew remove nethack
crew remove nethack4
crew remove newlisp
crew remove nftables
crew remove nginx
crew remove nmap
crew remove nmon
crew remove node
crew remove nodebrew
crew remove nping
crew remove npth
crew remove nvm
crew remove oc
crew remove ocaml
crew remove oci
crew remove octane
crew remove od1n
crew remove ondir
crew remove openblas
crew remove openconnect
crew remove openexr
crew remove openldap
crew remove openpam
crew remove openrtsp
crew remove optipng
crew remove osl
crew remove owl
crew remove p7zip
crew remove packer
crew remove packer_completion
crew remove pacparser
crew remove pagein
crew remove pagemon
crew remove pandoc
crew remove pangomm
crew remove parallel
crew remove pass
crew remove patchelf
crew remove patchutils
crew remove pavuk
crew remove pciutils
crew remove pcre
crew remove pcre2
crew remove pdfcrack
crew remove pdfgrep
crew remove percona_boost
crew remove percona_server
crew remove percona_toolkit
crew remove perl_gcstring_linebreak
crew remove perl_locale_gettext
crew remove perl_module_build
crew remove perl_read_key
crew remove perl_sgmls
crew remove perl_term_ansicolor
crew remove perl_text_charwidth
crew remove perl_text_wrapi18n
crew remove perl_time_hires
crew remove perl_xml_sax_parserfactory
crew remove perl_xml_simple
crew remove pexec
crew remove phive
crew remove php
crew remove php5
crew remove php7
crew remove pinentry
crew remove pipes_sh
crew remove pipesx_sh
crew remove platformsh
crew remove plowshare
crew remove pmd
crew remove pngcheck
crew remove poppler
crew remove poppler_data
crew remove popt
crew remove postgres
crew remove potrace
crew remove powerline_fonts
crew remove powerstat
crew remove progress
crew remove proj4
crew remove protobuf
crew remove proxychains
crew remove pulseaudio
crew remove putty
crew remove pv
crew remove pwgen
crew remove pycairo
crew remove pygobject
crew remove pygobject2
crew remove pygtk
crew remove q
crew remove qb64
crew remove qemacs
crew remove qemu
crew remove qpdf
crew remove qt
crew remove quakespasm
crew remove r
crew remove rack
crew remove radare2
crew remove ragel
crew remove ranger
crew remove readline7
crew remove recode
crew remove redis
crew remove regex_opt
crew remove remind
crew remove renameutils
crew remove ripgrep
crew remove rkhunter
crew remove rlwrap
crew remove rng_tools
crew remove rust
crew remove s3cmd
crew remove sane_backends
crew remove sane_frontends
crew remove sbt
crew remove scheme48
crew remove scite
crew remove scons
crew remove scrollz
crew remove scron
crew remove sejda_console
crew remove selenium_server_standalone
crew remove serf
crew remove sfk
crew remove sg3_utils
crew remove shared_mime_info
crew remove shhmsg
crew remove shhopt
crew remove shmux
crew remove shrinkpdf
crew remove shtool
crew remove siege
crew remove sl
crew remove sleuthkit
crew remove sluice
crew remove smem
crew remove smemstat
crew remove snap
crew remove snooze
crew remove snort
crew remove socat
crew remove spark
crew remove speedtest
crew remove speexdsp
crew remove sphinx
crew remove sqlmap
crew remove squashfs
crew remove sshfs
crew remove sshrc
crew remove sshuttle
crew remove stack
crew remove stow
crew remove strace
crew remove stressng
crew remove stunnel
crew remove sublime_merge
crew remove sublime_text
crew remove subversion
crew remove swatchdog
crew remove swig
crew remove swig1
crew remove syncthing
crew remove sysfsutils
crew remove tack
crew remove tcl
crew remove tcpdump
crew remove tcpstat
crew remove tcpwrappers
crew remove termcap
crew remove terraform
crew remove testdisk
crew remove texlive
crew remove textract
crew remove tidy
crew remove tig
crew remove tilp
crew remove tilp2
crew remove tina
crew remove tinycc
crew remove tinycore
crew remove tk
crew remove tldr
crew remove tmux
crew remove tox
crew remove tpp
crew remove traceroute
crew remove transmission
crew remove tre
crew remove txt2man
crew remove txt2regex
crew remove umockdev
crew remove units
crew remove unixodbc
crew remove unrar
crew remove unrtf
crew remove utf8proc
crew remove uwsgi
crew remove vagrant
crew remove vala
crew remove valgrind
crew remove vifm
crew remove virtualenv
crew remove waf
crew remove wayland
crew remove wbox
crew remove wdiff
crew remove weather
crew remove weston
crew remove whiptail
crew remove whitedb
crew remove whois
crew remove wine
crew remove wkhtmltox
crew remove wol
crew remove wp_cli
crew remove wput
crew remove wxwidgets
crew remove xbitmaps
crew remove xcb_util_cursor
crew remove xcb_util_image
crew remove xcb_util_keysyms
crew remove xcb_util_renderutil
crew remove xcb_util_wm
crew remove xdg_utils
crew remove xe
crew remove xmlclitools
crew remove xmlstarlet
crew remove xmlto
crew remove xorg_evdev_driver
crew remove xorg_fbdev_driver
crew remove xorg_intel_driver
crew remove xorg_lib
crew remove xorg_libinput_driver
crew remove xorg_nouveau_driver
crew remove xorg_server
crew remove xorg_synaptics_driver
crew remove xorg_vmmouse_driver
crew remove xorg_vmware_driver
crew remove xorg_wacom_driver
crew remove xscreensaver
crew remove xxhash
crew remove xz_java
crew remove yajl
crew remove yamllint
crew remove yarn
crew remove yelp_tools
crew remove yelp_xsl
crew remove zeromq
crew remove zile
crew remove zsh
crew remove zstd
crew remove zsync
exit